services:
  app:
    image: vc-cms:v1
    depends_on:
      - db
    ports:
      - 8020:80
    env_file: .env.local
  db:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
